// Global UI Action
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const OPEN_MENU = 'OPEN_MENU';
export const OPEN_SUBMENU = 'OPEN_SUBMENU';
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_RANDOM_THEME = 'CHANGE_RANDOM_THEME';
export const CHANGE_MODE = 'CHANGE_MODE';
export const CHANGE_GRADIENT = 'CHANGE_GRADIENT';
export const CHANGE_DECO = 'CHANGE_DECO';
export const CHANGE_BG_POSITION = 'CHANGE_BG_POSITION';
export const CHANGE_LAYOUT = 'CHANGE_LAYOUT';
export const CHANGE_DIRECTION = 'CHANGE_DIRECTION';
export const LOAD_PAGE = 'LOAD_PAGE';

// Tree Table
export const TOGGLE_TREE = 'TOGGLE_TREE';

// Redux Form
export const INIT = 'INIT';
export const CLEAR = 'CLEAR';

// Crud Table
export const FETCH_DATA = 'FETCH_DATA';
export const ADD_EMPTY_ROW = 'ADD_EMPTY_ROW';
export const UPDATE_ROW = 'UPDATE_ROW';
export const REMOVE_ROW = 'REMOVE_ROW';
export const EDIT_ROW = 'EDIT_ROW';
export const SAVE_ROW = 'SAVE_ROW';

// Crud Form Table
export const FETCH_DATA_FORM = 'FETCH_DATA_FORM';
export const ADD_NEW = 'ADD_NEW';
export const CLOSE_FORM = 'CLOSE_FORM';
export const SUBMIT_DATA = 'SUBMIT_DATA';
export const REMOVE_ROW_FORM = 'REMOVE_ROW_FORM';
export const EDIT_ROW_FORM = 'EDIT_ROW_FORM';

// Social Media
export const FETCH_TIMELINE_DATA = 'FETCH_TIMELINE_DATA';
export const FETCH_COMMENT_DATA = 'FETCH_COMMENT_DATA';
export const POST = 'POST';
export const POST_COMMENT = 'POST_COMMENT';
export const TOGGLE_LIKE = 'TOGGLE_LIKE';

// Ecommerce
export const FETCH_PRODUCT_DATA = 'FETCH_PRODUCT_DATA';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const SHOW_DETAIL_PRODUCT = 'SHOW_DETAIL_PRODUCT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const CHECKOUT = 'CHECKOUT';

// Contact
export const FETCH_CONTACT_DATA = 'FETCH_CONTACT_DATA';
export const SHOW_DETAIL_CONTACT = 'SHOW_DETAIL_CONTACT';
export const HIDE_DETAIL = 'HIDE_DETAIL';
export const ADD_CONTACT = 'ADD_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const SUBMIT_CONTACT = 'SUBMIT_CONTACT';
export const CLOSE_CONTACT_FORM = 'CLOSE_CONTACT_FORM';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const SEARCH_CONTACT = 'SEARCH_CONTACT';

// Chat
export const FETCH_CHAT_DATA = 'FETCH_CHAT_DATA';
export const SHOW_CHAT = 'SHOW_CHAT';
export const HIDE_CHAT = 'HIDE_CHAT';
export const SEND_CHAT = 'SEND_CHAT';
export const DELETE_CONVERSATION = 'DELETE_CONVERSATION';

// Email
export const FETCH_EMAIL_DATA = 'FETCH_EMAIL_DATA';
export const OPEN_MAIL = 'OPEN_MAIL';
export const FILTER_MAIL = 'FILTER_MAIL';
export const COMPOSE_MAIL = 'COMPOSE_MAIL';
export const DISCARD_MESSAGE = 'DISCARD_MESSAGE';
export const SEARCH_MAIL = 'SEARCH_MAIL';
export const SEND_MAIL = 'SEND_MAIL';
export const MOVE_TO = 'MOVE_TO';
export const DELETE_MAIL = 'DELETE_MAIL';
export const TOGGLE_STARED = 'TOGGLE_STARED';

// Calendar
export const FETCH_CALENDAR_DATA = 'FETCH_CALENDAR_DATA';
export const ADD_EVENT = 'ADD_EVENT';
export const DISCARD_EVENT = 'DISCARD_EVENT';
export const SUBMIT_EVENT = 'SUBMIT_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';

// Task Board
export const FETCH_BOARD_DATA = 'FETCH_BOARD_DATA';
export const ADD_BOARD = 'ADD_BOARD';
export const DISCARD_BOARD = 'DISCARD_BOARD';
export const SUBMIT_BOARD = 'SUBMIT_BOARD';
export const DELETE_BOARD = 'DELETE_BOARD';

// Notification Form
export const CLOSE_NOTIF = 'CLOSE_NOTIF';

// GYM Info

// Staff Login Info

export const LOGIN_STAFF = 'LOGIN_STAFF';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// Access

// Category
export const FETCH_CATEGORY_DATA = 'FETCH_CATEGORY_DATA';
export const SEARCH_CATEGORY_DATA = 'SEARCH_CATEGORY_DATA';
export const EDIT_CATEGORY_DATA = 'EDIT_CATEGORY_DATA';
export const DELETE_CATEGORY_DATA = 'DELETE_CATEGORY_DATA';
export const ADD_CATEGORY_DATA = 'ADD_CATEGORY_DATA';
export const ERROR_CATEGORY_DATA = 'ERROR_CATEGORY_DATA';
export const SHOW_DETAIL_CATEGORY = 'SHOW_DETAIL_CATEGORY';
export const HIDE_DETAIL_CATEGORY = 'HIDE_DETAIL_CATEGORY';
export const SUBMIT_CATEGORY_DATA = 'SUBMIT_CATEGORY_DATA';
export const CLOSE_CATEGORY_FORM = 'CLOSE_CATEGORY_FORM';
export const TOGGLE_FAVORITE_CATEGORY = 'TOGGLE_FAVORITE_CATEGORY';
export const SET_CATEGORY_DETAILS_FIELD = 'SET_CATEGORY_DETAILS_FIELD';
export const LOADING_ACTION_CATEGORY = 'LOADING_ACTION_CATEGORY';

// Package
export const FETCH_PACKAGE_DATA = 'FETCH_PACKAGE_DATA';
export const SEARCH_PACKAGE_DATA = 'SEARCH_PACKAGE_DATA';
export const EDIT_PACKAGE_DATA = 'EDIT_PACKAGE_DATA';
export const DELETE_PACKAGE_DATA = 'DELETE_PACKAGE_DATA';
export const ADD_PACKAGE_DATA = 'ADD_PACKAGE_DATA';
export const ERROR_PACKAGE_DATA = 'ERROR_PACKAGE_DATA';
export const SHOW_DETAIL_PACKAGE = 'SHOW_DETAIL_PACKAGE';
export const HIDE_DETAIL_PACKAGE = 'HIDE_DETAIL_PACKAGE';
export const SUBMIT_PACKAGE_DATA = 'SUBMIT_PACKAGE_DATA';
export const CLOSE_PACKAGE_FORM = 'CLOSE_PACKAGE_FORM';
export const TOGGLE_FAVORITE_PACKAGE = 'TOGGLE_FAVORITE_PACKAGE';
export const SET_PACKAGE_DETAILS_FIELD = 'SET_PACKAGE_DETAILS_FIELD';
export const LOADING_ACTION_PACKAGE = 'LOADING_ACTION_PACKAGE';

// Payment Method
export const FETCH_PAYMENT_METHOD_DATA = 'FETCH_PAYMENT_METHOD_DATA';
export const SEARCH_PAYMENT_METHOD_DATA = 'SEARCH_PAYMENT_METHOD_DATA';
export const EDIT_PAYMENT_METHOD_DATA = 'EDIT_PAYMENT_METHOD_DATA';
export const DELETE_PAYMENT_METHOD_DATA = 'DELETE_PAYMENT_METHOD_DATA';
export const ADD_PAYMENT_METHOD_DATA = 'ADD_PAYMENT_METHOD_DATA';
export const ERROR_PAYMENT_METHOD_DATA = 'ERROR_PAYMENT_METHOD_DATA';
export const SHOW_DETAIL_PAYMENT_METHOD = 'SHOW_DETAIL_PAYMENT_METHOD';
export const HIDE_DETAIL_PAYMENT_METHOD = 'HIDE_DETAIL_PAYMENT_METHOD';
export const SUBMIT_PAYMENT_METHOD_DATA = 'SUBMIT_PAYMENT_METHOD_DATA';
export const CLOSE_PAYMENT_METHOD_FORM = 'CLOSE_PAYMENT_METHOD_FORM';
export const TOGGLE_FAVORITE_PAYMENT_METHOD = 'TOGGLE_FAVORITE_PAYMENT_METHOD';
export const SET_PAYMENT_METHOD_DETAILS_FIELD = 'SET_PAYMENT_METHOD_DETAILS_FIELD';
export const LOADING_ACTION_PAYMENT_METHOD = 'LOADING_ACTION_PAYMENT_METHOD';


// Staff
export const FETCH_STAFF_DATA = 'FETCH_STAFF_DATA';
export const SEARCH_STAFF_DATA = 'SEARCH_STAFF_DATA';
export const EDIT_STAFF_DATA = 'EDIT_STAFF_DATA';
export const DELETE_STAFF_DATA = 'DELETE_STAFF_DATA';
export const ADD_STAFF_DATA = 'ADD_STAFF_DATA';
export const ERROR_STAFF_DATA = 'ERROR_STAFF_DATA';
export const SHOW_DETAIL_STAFF = 'SHOW_DETAIL_STAFF';
export const HIDE_DETAIL_STAFF = 'HIDE_DETAIL_STAFF';
export const SUBMIT_STAFF_DATA = 'SUBMIT_STAFF_DATA';
export const CLOSE_STAFF_FORM = 'CLOSE_STAFF_FORM';
export const TOGGLE_FAVORITE_STAFF = 'TOGGLE_FAVORITE_STAFF';
export const SET_STAFF_DETAILS_FIELD = 'SET_STAFF_DETAILS_FIELD';
export const LOADING_ACTION_STAFF = 'LOADING_ACTION_STAFF';
export const FETCH_ACCESS_DATA = 'FETCH_ACCESS_DATA';


// Class
export const FETCH_CLASS_DATA = 'FETCH_CLASS_DATA';
export const SEARCH_CLASS_DATA = 'SEARCH_CLASS_DATA';
export const EDIT_CLASS_DATA = 'EDIT_CLASS_DATA';
export const DELETE_CLASS_DATA = 'DELETE_CLASS_DATA';
export const ADD_CLASS_DATA = 'ADD_CLASS_DATA';
export const ERROR_CLASS_DATA = 'ERROR_CLASS_DATA';
export const SHOW_DETAIL_CLASS = 'SHOW_DETAIL_CLASS';
export const HIDE_DETAIL_CLASS = 'HIDE_DETAIL_CLASS';
export const SUBMIT_CLASS_DATA = 'SUBMIT_CLASS_DATA';
export const CLOSE_CLASS_FORM = 'CLOSE_CLASS_FORM';
export const TOGGLE_FAVORITE_CLASS = 'TOGGLE_FAVORITE_CLASS';
export const SET_CLASS_DETAILS_FIELD = 'SET_CLASS_DETAILS_FIELD';
export const LOADING_ACTION_CLASS = 'LOADING_ACTION_CLASS';


// Purpose
export const FETCH_PURPOSE_DATA = 'FETCH_PURPOSE_DATA';
export const SEARCH_PURPOSE_DATA = 'SEARCH_PURPOSE_DATA';
export const EDIT_PURPOSE_DATA = 'EDIT_PURPOSE_DATA';
export const DELETE_PURPOSE_DATA = 'DELETE_PURPOSE_DATA';
export const ADD_PURPOSE_DATA = 'ADD_PURPOSE_DATA';
export const ERROR_PURPOSE_DATA = 'ERROR_PURPOSE_DATA';
export const SHOW_DETAIL_PURPOSE = 'SHOW_DETAIL_PURPOSE';
export const HIDE_DETAIL_PURPOSE = 'HIDE_DETAIL_PURPOSE';
export const SUBMIT_PURPOSE_DATA = 'SUBMIT_PURPOSE_DATA';
export const CLOSE_PURPOSE_FORM = 'CLOSE_PURPOSE_FORM';
export const TOGGLE_FAVORITE_PURPOSE = 'TOGGLE_FAVORITE_PURPOSE';
export const SET_PURPOSE_DETAILS_FIELD = 'SET_PURPOSE_DETAILS_FIELD';
export const LOADING_ACTION_PURPOSE = 'LOADING_ACTION_PURPOSE';
export const HANDLE_NEXT_STEP = 'HANDLE_NEXT_STEP';

// Registration

export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';


// Subscription


// Enquiry
export const FETCH_ENQUIRY_DATA = 'FETCH_ENQUIRY_DATA';
export const SEARCH_ENQUIRY_DATA = 'SEARCH_ENQUIRY_DATA';
export const EDIT_ENQUIRY_DATA = 'EDIT_ENQUIRY_DATA';
export const DELETE_ENQUIRY_DATA = 'DELETE_ENQUIRY_DATA';
export const ADD_ENQUIRY_DATA = 'ADD_ENQUIRY_DATA';
export const ERROR_ENQUIRY_DATA = 'ERROR_ENQUIRY_DATA';
export const SHOW_DETAIL_ENQUIRY = 'SHOW_DETAIL_ENQUIRY';
export const HIDE_DETAIL_ENQUIRY = 'HIDE_DETAIL_ENQUIRY';
export const SUBMIT_ENQUIRY_DATA = 'SUBMIT_ENQUIRY_DATA';
export const CLOSE_ENQUIRY_FORM = 'CLOSE_ENQUIRY_FORM';
export const TOGGLE_FAVORITE_ENQUIRY = 'TOGGLE_FAVORITE_ENQUIRY';
export const SET_ENQUIRY_DETAILS_FIELD = 'SET_ENQUIRY_DETAILS_FIELD';
export const LOADING_ACTION_ENQUIRY = 'LOADING_ACTION_ENQUIRY';


// Add member
export const FETCH_ADD_MEMBER_DATA = 'FETCH_ADD_MEMBER_DATA';
export const SEARCH_ADD_MEMBER_DATA = 'SEARCH_ADD_MEMBER_DATA';
export const EDIT_ADD_MEMBER_DATA = 'EDIT_ADD_MEMBER_DATA';
export const DELETE_ADD_MEMBER_DATA = 'DELETE_ADD_MEMBER_DATA';
export const ADD_ADD_MEMBER_DATA = 'ADD_ADD_MEMBER_DATA';
export const ERROR_ADD_MEMBER_DATA = 'ERROR_ADD_MEMBER_DATA';
export const SHOW_DETAIL_ADD_MEMBER = 'SHOW_DETAIL_ADD_MEMBER';
export const HIDE_DETAIL_ADD_MEMBER = 'HIDE_DETAIL_ADD_MEMBER';
export const SUBMIT_ADD_MEMBER_DATA = 'SUBMIT_ADD_MEMBER_DATA';
export const CLOSE_ADD_MEMBER_FORM = 'CLOSE_ADD_MEMBER_FORM';
export const TOGGLE_FAVORITE_ADD_MEMBER = 'TOGGLE_FAVORITE_ADD_MEMBER';
export const SET_ADD_MEMBER_DETAILS_FIELD = 'SET_ADD_MEMBER_DETAILS_FIELD';
export const LOADING_ACTION_ADD_MEMBER = 'LOADING_ACTION_ADD_MEMBER';
export const VIEW_PROFILE = 'VIEW_PROFILE';
export const SET_FILTER_VALUE = 'SET_FILTER_VALUE';
export const FETCH_GYM_INFO = 'FETCH_GYM_INFO';


// Expense/Income
export const FETCH_EXPENSE_INCOME_DATA = 'FETCH_EXPENSE_INCOME_DATA';
export const SEARCH_EXPENSE_INCOME_DATA = 'SEARCH_EXPENSE_INCOME_DATA';
export const EDIT_EXPENSE_INCOME_DATA = 'EDIT_EXPENSE_INCOME_DATA';
export const DELETE_EXPENSE_INCOME_DATA = 'DELETE_EXPENSE_INCOME_DATA';
export const ADD_EXPENSE_INCOME_DATA = 'ADD_EXPENSE_INCOME_DATA';
export const ERROR_EXPENSE_INCOME_DATA = 'ERROR_EXPENSE_INCOME_DATA';
export const SHOW_DETAIL_EXPENSE_INCOME = 'SHOW_DETAIL_EXPENSE_INCOME';
export const HIDE_DETAIL_EXPENSE_INCOME = 'HIDE_DETAIL_EXPENSE_INCOME';
export const SUBMIT_EXPENSE_INCOME_DATA = 'SUBMIT_EXPENSE_INCOME_DATA';
export const CLOSE_EXPENSE_INCOME_FORM = 'CLOSE_EXPENSE_INCOME_FORM';
export const TOGGLE_FAVORITE_EXPENSE_INCOME = 'TOGGLE_FAVORITE_EXPENSE_INCOME';
export const SET_EXPENSE_INCOME_DETAILS_FIELD = 'SET_EXPENSE_INCOME_DETAILS_FIELD';
export const LOADING_ACTION_EXPENSE_INCOME = 'LOADING_ACTION_EXPENSE_INCOME';
export const HANDLE_FROM_TO_FILTER = 'HANDLE_FROM_TO_FILTER';


// Measurement
export const FETCH_MEASUREMENT_DATA = 'FETCH_MEASUREMENT_DATA';
export const SEARCH_MEASUREMENT_DATA = 'SEARCH_MEASUREMENT_DATA';
export const EDIT_MEASUREMENT_DATA = 'EDIT_MEASUREMENT_DATA';
export const DELETE_MEASUREMENT_DATA = 'DELETE_MEASUREMENT_DATA';
export const ADD_MEASUREMENT_DATA = 'ADD_MEASUREMENT_DATA';
export const ERROR_MEASUREMENT_DATA = 'ERROR_MEASUREMENT_DATA';
export const SHOW_DETAIL_MEASUREMENT = 'SHOW_DETAIL_MEASUREMENT';
export const HIDE_DETAIL_MEASUREMENT = 'HIDE_DETAIL_MEASUREMENT';
export const SUBMIT_MEASUREMENT_DATA = 'SUBMIT_MEASUREMENT_DATA';
export const CLOSE_MEASUREMENT_FORM = 'CLOSE_MEASUREMENT_FORM';
export const TOGGLE_FAVORITE_MEASUREMENT = 'TOGGLE_FAVORITE_MEASUREMENT';
export const SET_MEASUREMENT_DETAILS_FIELD = 'SET_MEASUREMENT_DETAILS_FIELD';
export const LOADING_ACTION_MEASUREMENT = 'LOADING_ACTION_MEASUREMENT';


// Class Subscription
export const FETCH_CLASS_SUBSCRIPTION_DATA = 'FETCH_CLASS_SUBSCRIPTION_DATA';
export const SEARCH_CLASS_SUBSCRIPTION_DATA = 'SEARCH_CLASS_SUBSCRIPTION_DATA';
export const EDIT_CLASS_SUBSCRIPTION_DATA = 'EDIT_CLASS_SUBSCRIPTION_DATA';
export const DELETE_CLASS_SUBSCRIPTION_DATA = 'DELETE_CLASS_SUBSCRIPTION_DATA';
export const ADD_CLASS_SUBSCRIPTION_DATA = 'ADD_CLASS_SUBSCRIPTION_DATA';
export const ERROR_CLASS_SUBSCRIPTION_DATA = 'ERROR_CLASS_SUBSCRIPTION_DATA';
export const SHOW_DETAIL_CLASS_SUBSCRIPTION = 'SHOW_DETAIL_CLASS_SUBSCRIPTION';
export const HIDE_DETAIL_CLASS_SUBSCRIPTION = 'HIDE_DETAIL_CLASS_SUBSCRIPTION';
export const SUBMIT_CLASS_SUBSCRIPTION_DATA = 'SUBMIT_CLASS_SUBSCRIPTION_DATA';
export const CLOSE_CLASS_SUBSCRIPTION_FORM = 'CLOSE_CLASS_SUBSCRIPTION_FORM';
export const TOGGLE_FAVORITE_CLASS_SUBSCRIPTION = 'TOGGLE_FAVORITE_CLASS_SUBSCRIPTION';
export const SET_CLASS_SUBSCRIPTION_DETAILS_FIELD = 'SET_CLASS_SUBSCRIPTION_DETAILS_FIELD';
export const LOADING_ACTION_CLASS_SUBSCRIPTION = 'LOADING_ACTION_CLASS_SUBSCRIPTION';


// Vendor Package Subscription
export const FETCH_VENDOR_PACKAGE_SUBSCRIPTION_DATA = 'FETCH_VENDOR_PACKAGE_SUBSCRIPTION_DATA';
export const SEARCH_VENDOR_PACKAGE_SUBSCRIPTION_DATA = 'SEARCH_VENDOR_PACKAGE_SUBSCRIPTION_DATA';
export const EDIT_VENDOR_PACKAGE_SUBSCRIPTION_DATA = 'EDIT_VENDOR_PACKAGE_SUBSCRIPTION_DATA';
export const DELETE_VENDOR_PACKAGE_SUBSCRIPTION_DATA = 'DELETE_VENDOR_PACKAGE_SUBSCRIPTION_DATA';
export const ADD_VENDOR_PACKAGE_SUBSCRIPTION_DATA = 'ADD_VENDOR_PACKAGE_SUBSCRIPTION_DATA';
export const ERROR_VENDOR_PACKAGE_SUBSCRIPTION_DATA = 'ERROR_VENDOR_PACKAGE_SUBSCRIPTION_DATA';
export const SHOW_DETAIL_VENDOR_PACKAGE_SUBSCRIPTION = 'SHOW_DETAIL_VENDOR_PACKAGE_SUBSCRIPTION';
export const HIDE_DETAIL_VENDOR_PACKAGE_SUBSCRIPTION = 'HIDE_DETAIL_VENDOR_PACKAGE_SUBSCRIPTION';
export const SUBMIT_VENDOR_PACKAGE_SUBSCRIPTION_DATA = 'SUBMIT_VENDOR_PACKAGE_SUBSCRIPTION_DATA';
export const CLOSE_VENDOR_PACKAGE_SUBSCRIPTION_FORM = 'CLOSE_VENDOR_PACKAGE_SUBSCRIPTION_FORM';
export const TOGGLE_FAVORITE_VENDOR_PACKAGE_SUBSCRIPTION = 'TOGGLE_FAVORITE_VENDOR_PACKAGE_SUBSCRIPTION';
export const SET_VENDOR_PACKAGE_SUBSCRIPTION_DETAILS_FIELD = 'SET_VENDOR_PACKAGE_SUBSCRIPTION_DETAILS_FIELD';
export const LOADING_ACTION_VENDOR_PACKAGE_SUBSCRIPTION = 'LOADING_ACTION_VENDOR_PACKAGE_SUBSCRIPTION';


// Purpose Subscription
export const FETCH_PURPOSE_SUBSCRIPTION_DATA = 'FETCH_PURPOSE_SUBSCRIPTION_DATA';
export const SEARCH_PURPOSE_SUBSCRIPTION_DATA = 'SEARCH_PURPOSE_SUBSCRIPTION_DATA';
export const EDIT_PURPOSE_SUBSCRIPTION_DATA = 'EDIT_PURPOSE_SUBSCRIPTION_DATA';
export const DELETE_PURPOSE_SUBSCRIPTION_DATA = 'DELETE_PURPOSE_SUBSCRIPTION_DATA';
export const ADD_PURPOSE_SUBSCRIPTION_DATA = 'ADD_PURPOSE_SUBSCRIPTION_DATA';
export const ERROR_PURPOSE_SUBSCRIPTION_DATA = 'ERROR_PURPOSE_SUBSCRIPTION_DATA';
export const SHOW_DETAIL_PURPOSE_SUBSCRIPTION = 'SHOW_DETAIL_PURPOSE_SUBSCRIPTION';
export const HIDE_DETAIL_PURPOSE_SUBSCRIPTION = 'HIDE_DETAIL_PURPOSE_SUBSCRIPTION';
export const SUBMIT_PURPOSE_SUBSCRIPTION_DATA = 'SUBMIT_PURPOSE_SUBSCRIPTION_DATA';
export const CLOSE_PURPOSE_SUBSCRIPTION_FORM = 'CLOSE_PURPOSE_SUBSCRIPTION_FORM';
export const TOGGLE_FAVORITE_PURPOSE_SUBSCRIPTION = 'TOGGLE_FAVORITE_PURPOSE_SUBSCRIPTION';
export const SET_PURPOSE_SUBSCRIPTION_DETAILS_FIELD = 'SET_PURPOSE_SUBSCRIPTION_DETAILS_FIELD';
export const LOADING_ACTION_PURPOSE_SUBSCRIPTION = 'LOADING_ACTION_PURPOSE_SUBSCRIPTION';


// Media
export const FETCH_MEDIA_DATA = 'FETCH_MEDIA_DATA';
export const SEARCH_MEDIA_DATA = 'SEARCH_MEDIA_DATA';
export const EDIT_MEDIA_DATA = 'EDIT_MEDIA_DATA';
export const DELETE_MEDIA_DATA = 'DELETE_MEDIA_DATA';
export const ADD_MEDIA_DATA = 'ADD_MEDIA_DATA';
export const ERROR_MEDIA_DATA = 'ERROR_MEDIA_DATA';
export const SHOW_DETAIL_MEDIA = 'SHOW_DETAIL_MEDIA';
export const HIDE_DETAIL_MEDIA = 'HIDE_DETAIL_MEDIA';
export const SUBMIT_MEDIA_DATA = 'SUBMIT_MEDIA_DATA';
export const CLOSE_MEDIA_FORM = 'CLOSE_MEDIA_FORM';
export const TOGGLE_FAVORITE_MEDIA = 'TOGGLE_FAVORITE_MEDIA';
export const SET_MEDIA_DETAILS_FIELD = 'SET_MEDIA_DETAILS_FIELD';
export const LOADING_ACTION_MEDIA = 'LOADING_ACTION_MEDIA';


// Product Type
export const FETCH_PRODUCT_TYPE_DATA = 'FETCH_PRODUCT_TYPE_DATA';
export const SEARCH_PRODUCT_TYPE_DATA = 'SEARCH_PRODUCT_TYPE_DATA';
export const EDIT_PRODUCT_TYPE_DATA = 'EDIT_PRODUCT_TYPE_DATA';
export const DELETE_PRODUCT_TYPE_DATA = 'DELETE_PRODUCT_TYPE_DATA';
export const ADD_PRODUCT_TYPE_DATA = 'ADD_PRODUCT_TYPE_DATA';
export const ERROR_PRODUCT_TYPE_DATA = 'ERROR_PRODUCT_TYPE_DATA';
export const SHOW_DETAIL_PRODUCT_TYPE = 'SHOW_DETAIL_PRODUCT_TYPE';
export const HIDE_DETAIL_PRODUCT_TYPE = 'HIDE_DETAIL_PRODUCT_TYPE';
export const SUBMIT_PRODUCT_TYPE_DATA = 'SUBMIT_PRODUCT_TYPE_DATA';
export const CLOSE_PRODUCT_TYPE_FORM = 'CLOSE_PRODUCT_TYPE_FORM';
export const TOGGLE_FAVORITE_PRODUCT_TYPE = 'TOGGLE_FAVORITE_PRODUCT_TYPE';
export const SET_PRODUCT_TYPE_DETAILS_FIELD = 'SET_PRODUCT_TYPE_DETAILS_FIELD';
export const LOADING_ACTION_PRODUCT_TYPE = 'LOADING_ACTION_PRODUCT_TYPE';

// Product
export const FETCH_PRODUCT_SHOPING_DATA = 'FETCH_PRODUCT_SHOPING_DATA';
export const SEARCH_PRODUCT_SHOPING_DATA = 'SEARCH_PRODUCT_SHOPING_DATA';
export const EDIT_PRODUCT_SHOPING_DATA = 'EDIT_PRODUCT_SHOPING_DATA';
export const DELETE_PRODUCT_SHOPING_DATA = 'DELETE_PRODUCT_SHOPING_DATA';
export const ADD_PRODUCT_SHOPING_DATA = 'ADD_PRODUCT_SHOPING_DATA';
export const ERROR_PRODUCT_SHOPING_DATA = 'ERROR_PRODUCT_SHOPING_DATA';
export const SHOW_DETAIL_PRODUCT_SHOPING = 'SHOW_DETAIL_PRODUCT_SHOPING';
export const HIDE_DETAIL_PRODUCT_SHOPING = 'HIDE_DETAIL_PRODUCT_SHOPING';
export const SUBMIT_PRODUCT_SHOPING_DATA = 'SUBMIT_PRODUCT_SHOPING_DATA';
export const CLOSE_PRODUCT_SHOPING_FORM = 'CLOSE_PRODUCT_SHOPING_FORM';
export const TOGGLE_FAVORITE_PRODUCT_SHOPING = 'TOGGLE_FAVORITE_PRODUCT_SHOPING';
export const SET_PRODUCT_SHOPING_DETAILS_FIELD = 'SET_PRODUCT_SHOPING_DETAILS_FIELD';
export const LOADING_ACTION_PRODUCT_SHOPING = 'LOADING_ACTION_PRODUCT_SHOPING';
export const FETCH_PRODUCT_QUANTITY = 'FETCH_PRODUCT_QUANTITY';
// Brand Unit
export const FETCH_BRAND_UNIT_DATA = 'FETCH_BRAND_UNIT_DATA';
export const SEARCH_BRAND_UNIT_DATA = 'SEARCH_BRAND_UNIT_DATA';
export const EDIT_BRAND_UNIT_DATA = 'EDIT_BRAND_UNIT_DATA';
export const DELETE_BRAND_UNIT_DATA = 'DELETE_BRAND_UNIT_DATA';
export const ADD_BRAND_UNIT_DATA = 'ADD_BRAND_UNIT_DATA';
export const ERROR_BRAND_UNIT_DATA = 'ERROR_BRAND_UNIT_DATA';
export const SHOW_DETAIL_BRAND_UNIT = 'SHOW_DETAIL_BRAND_UNIT';
export const HIDE_DETAIL_BRAND_UNIT = 'HIDE_DETAIL_BRAND_UNIT';
export const SUBMIT_BRAND_UNIT_DATA = 'SUBMIT_BRAND_UNIT_DATA';
export const CLOSE_BRAND_UNIT_FORM = 'CLOSE_BRAND_UNIT_FORM';
export const TOGGLE_FAVORITE_BRAND_UNIT = 'TOGGLE_FAVORITE_BRAND_UNIT';
export const SET_BRAND_UNIT_DETAILS_FIELD = 'SET_BRAND_UNIT_DETAILS_FIELD';
export const LOADING_ACTION_BRAND_UNIT = 'LOADING_ACTION_BRAND_UNIT';


// Purchase
export const FETCH_PURCHASE_DATA = 'FETCH_PURCHASE_DATA';
export const SEARCH_PURCHASE_DATA = 'SEARCH_PURCHASE_DATA';
export const EDIT_PURCHASE_DATA = 'EDIT_PURCHASE_DATA';
export const DELETE_PURCHASE_DATA = 'DELETE_PURCHASE_DATA';
export const ADD_PURCHASE_DATA = 'ADD_PURCHASE_DATA';
export const ERROR_PURCHASE_DATA = 'ERROR_PURCHASE_DATA';
export const SHOW_DETAIL_PURCHASE = 'SHOW_DETAIL_PURCHASE';
export const HIDE_DETAIL_PURCHASE = 'HIDE_DETAIL_PURCHASE';
export const SUBMIT_PURCHASE_DATA = 'SUBMIT_PURCHASE_DATA';
export const CLOSE_PURCHASE_FORM = 'CLOSE_PURCHASE_FORM';
export const TOGGLE_FAVORITE_PURCHASE = 'TOGGLE_FAVORITE_PURCHASE';
export const SET_PURCHASE_DETAILS_FIELD = 'SET_PURCHASE_DETAILS_FIELD';
export const LOADING_ACTION_PURCHASE = 'LOADING_ACTION_PURCHASE';
export const SET_VALUE_IN_CART = 'SET_VALUE_IN_CART';
export const RESET_CART = 'RESET_CART';
export const DELETE_CART_VALUE = 'DELETE_CART_VALUE';
export const SET_ACCOUNT_DATA = 'SET_ACCOUNT_DATA';
export const HANDLE_BACK_STEP = 'HANDLE_BACK_STEP';
export const SHOPING_AGAIN = 'SHOPING_AGAIN';
export const SET_BILL_INFO_DATA = 'SET_BILL_INFO_DATA';
export const SET_DISCOUNT = 'SET_DISCOUNT';
export const SET_DISCOUNT_IN_VALUE = 'SET_DISCOUNT_IN_VALUE';
export const GET_GYM_INFO_DATA = 'GET_GYM_INFO_DATA';

// Workout Nutrition
export const FETCH_WORKOUT_NUTRITION_DATA = 'FETCH_WORKOUT_NUTRITION_DATA';
export const SEARCH_WORKOUT_NUTRITION_DATA = 'SEARCH_WORKOUT_NUTRITION_DATA';
export const EDIT_WORKOUT_NUTRITION_DATA = 'EDIT_WORKOUT_NUTRITION_DATA';
export const DELETE_WORKOUT_NUTRITION_DATA = 'DELETE_WORKOUT_NUTRITION_DATA';
export const ADD_WORKOUT_NUTRITION_DATA = 'ADD_WORKOUT_NUTRITION_DATA';
export const ERROR_WORKOUT_NUTRITION_DATA = 'ERROR_WORKOUT_NUTRITION_DATA';
export const SHOW_DETAIL_WORKOUT_NUTRITION = 'SHOW_DETAIL_WORKOUT_NUTRITION';
export const HIDE_DETAIL_WORKOUT_NUTRITION = 'HIDE_DETAIL_WORKOUT_NUTRITION';
export const SUBMIT_WORKOUT_NUTRITION_DATA = 'SUBMIT_WORKOUT_NUTRITION_DATA';
export const CLOSE_WORKOUT_NUTRITION_FORM = 'CLOSE_WORKOUT_NUTRITION_FORM';
export const TOGGLE_FAVORITE_WORKOUT_NUTRITION = 'TOGGLE_FAVORITE_WORKOUT_NUTRITION';
export const SET_WORKOUT_NUTRITION_DETAILS_FIELD = 'SET_WORKOUT_NUTRITION_DETAILS_FIELD';
export const LOADING_ACTION_WORKOUT_NUTRITION = 'LOADING_ACTION_WORKOUT_NUTRITION';


// Account info
export const FETCH_ACCOUNT_INFO_DATA = 'FETCH_ACCOUNT_INFO_DATA';
export const SEARCH_ACCOUNT_INFO_DATA = 'SEARCH_ACCOUNT_INFO_DATA';
export const EDIT_ACCOUNT_INFO_DATA = 'EDIT_ACCOUNT_INFO_DATA';
export const DELETE_ACCOUNT_INFO_DATA = 'DELETE_ACCOUNT_INFO_DATA';
export const ADD_ACCOUNT_INFO_DATA = 'ADD_ACCOUNT_INFO_DATA';
export const ERROR_ACCOUNT_INFO_DATA = 'ERROR_ACCOUNT_INFO_DATA';
export const SHOW_DETAIL_ACCOUNT_INFO = 'SHOW_DETAIL_ACCOUNT_INFO';
export const HIDE_DETAIL_ACCOUNT_INFO = 'HIDE_DETAIL_ACCOUNT_INFO';
export const SUBMIT_ACCOUNT_INFO_DATA = 'SUBMIT_ACCOUNT_INFO_DATA';
export const CLOSE_ACCOUNT_INFO_FORM = 'CLOSE_ACCOUNT_INFO_FORM';
export const TOGGLE_FAVORITE_ACCOUNT_INFO = 'TOGGLE_FAVORITE_ACCOUNT_INFO';
export const SET_ACCOUNT_INFO_DETAILS_FIELD = 'SET_ACCOUNT_INFO_DETAILS_FIELD';
export const LOADING_ACTION_ACCOUNT_INFO = 'LOADING_ACTION_ACCOUNT_INFO';

// Invoice In
export const FETCH_INVOICE_IN_DATA = 'FETCH_INVOICE_IN_DATA';
export const SEARCH_INVOICE_IN_DATA = 'SEARCH_INVOICE_IN_DATA';
export const EDIT_INVOICE_IN_DATA = 'EDIT_INVOICE_IN_DATA';
export const DELETE_INVOICE_IN_DATA = 'DELETE_INVOICE_IN_DATA';
export const ADD_INVOICE_IN_DATA = 'ADD_INVOICE_IN_DATA';
export const ERROR_INVOICE_IN_DATA = 'ERROR_INVOICE_IN_DATA';
export const SHOW_DETAIL_INVOICE_IN = 'SHOW_DETAIL_INVOICE_IN';
export const HIDE_DETAIL_INVOICE_IN = 'HIDE_DETAIL_INVOICE_IN';
export const SUBMIT_INVOICE_IN_DATA = 'SUBMIT_INVOICE_IN_DATA';
export const CLOSE_INVOICE_IN_FORM = 'CLOSE_INVOICE_IN_FORM';
export const TOGGLE_FAVORITE_INVOICE_IN = 'TOGGLE_FAVORITE_INVOICE_IN';
export const SET_INVOICE_IN_DETAILS_FIELD = 'SET_INVOICE_IN_DETAILS_FIELD';
export const LOADING_ACTION_INVOICE_IN = 'LOADING_ACTION_INVOICE_IN';

// Order Summary
export const FETCH_ORDER_SUMMARY_DATA = 'FETCH_ORDER_SUMMARY_DATA';
export const SEARCH_ORDER_SUMMARY_DATA = 'SEARCH_ORDER_SUMMARY_DATA';
export const EDIT_ORDER_SUMMARY_DATA = 'EDIT_ORDER_SUMMARY_DATA';
export const DELETE_ORDER_SUMMARY_DATA = 'DELETE_ORDER_SUMMARY_DATA';
export const ADD_ORDER_SUMMARY_DATA = 'ADD_ORDER_SUMMARY_DATA';
export const ERROR_ORDER_SUMMARY_DATA = 'ERROR_ORDER_SUMMARY_DATA';
export const SHOW_DETAIL_ORDER_SUMMARY = 'SHOW_DETAIL_ORDER_SUMMARY';
export const HIDE_DETAIL_ORDER_SUMMARY = 'HIDE_DETAIL_ORDER_SUMMARY';
export const SUBMIT_ORDER_SUMMARY_DATA = 'SUBMIT_ORDER_SUMMARY_DATA';
export const CLOSE_ORDER_SUMMARY_FORM = 'CLOSE_ORDER_SUMMARY_FORM';
export const TOGGLE_FAVORITE_ORDER_SUMMARY = 'TOGGLE_FAVORITE_ORDER_SUMMARY';
export const SET_ORDER_SUMMARY_DETAILS_FIELD = 'SET_ORDER_SUMMARY_DETAILS_FIELD';
export const LOADING_ACTION_ORDER_SUMMARY = 'LOADING_ACTION_ORDER_SUMMARY';


// Account
export const FETCH_ACCOUNT_DATA = 'FETCH_ACCOUNT_DATA';
export const SEARCH_ACCOUNT_DATA = 'SEARCH_ACCOUNT_DATA';
export const EDIT_ACCOUNT_DATA = 'EDIT_ACCOUNT_DATA';
export const DELETE_ACCOUNT_DATA = 'DELETE_ACCOUNT_DATA';
export const ADD_ACCOUNT_DATA = 'ADD_ACCOUNT_DATA';
export const ERROR_ACCOUNT_DATA = 'ERROR_ACCOUNT_DATA';
export const SHOW_DETAIL_ACCOUNT = 'SHOW_DETAIL_ACCOUNT';
export const HIDE_DETAIL_ACCOUNT = 'HIDE_DETAIL_ACCOUNT';
export const SUBMIT_ACCOUNT_DATA = 'SUBMIT_ACCOUNT_DATA';
export const CLOSE_ACCOUNT_FORM = 'CLOSE_ACCOUNT_FORM';
export const TOGGLE_FAVORITE_ACCOUNT = 'TOGGLE_FAVORITE_ACCOUNT';
export const SET_ACCOUNT_DETAILS_FIELD = 'SET_ACCOUNT_DETAILS_FIELD';
export const LOADING_ACTION_ACCOUNT = 'LOADING_ACTION_ACCOUNT';


// Report
export const FETCH_PENDING_PAYMENTS_DATA = 'FETCH_PENDING_PAYMENTS_DATA';
export const FETCH_REPORTS_DATA = 'FETCH_REPORTS_DATA';
export const FETCH_EXPIRING_MEMBERSHIPS_DATA = 'FETCH_EXPIRING_MEMBERSHIPS_DATA';
export const FETCH_EXPIRED_MEMBERS_DATA = 'FETCH_EXPIRED_MEMBERS_DATA';
export const FETCH_NON_ACTIVE_MEMBERS_DATA = 'FETCH_NON_ACTIVE_MEMBERS_DATA';
export const FETCH_CLASSES_DATA = 'FETCH_CLASSES_DATA';
export const FETCH_ALL_NEW_REGISTERED_DATA = 'FETCH_ALL_NEW_REGISTERED_DATA';
export const FETCH_ALL_RENEWED_MEMBERSHIP_DATA = 'FETCH_ALL_RENEWED_MEMBERSHIP_DATA';
export const SET_ATTENDANCE = 'SET_ATTENDANCE';
export const ERROR_REPORTS_DATA = 'ERROR_REPORTS_DATA';
export const UPDATED_DATA = 'UPDATED_DATA';


// Sale
export const FETCH_SALE_DATA = 'FETCH_SALE_DATA';
export const SEARCH_SALE_DATA = 'SEARCH_SALE_DATA';
export const EDIT_SALE_DATA = 'EDIT_SALE_DATA';
export const DELETE_SALE_DATA = 'DELETE_SALE_DATA';
export const ADD_SALE_DATA = 'ADD_SALE_DATA';
export const ERROR_SALE_DATA = 'ERROR_SALE_DATA';
export const SHOW_DETAIL_SALE = 'SHOW_DETAIL_SALE';
export const HIDE_DETAIL_SALE = 'HIDE_DETAIL_SALE';
export const SUBMIT_SALE_DATA = 'SUBMIT_SALE_DATA';
export const CLOSE_SALE_FORM = 'CLOSE_SALE_FORM';
export const TOGGLE_FAVORITE_SALE = 'TOGGLE_FAVORITE_SALE';
export const SET_SALE_DETAILS_FIELD = 'SET_SALE_DETAILS_FIELD';
export const LOADING_ACTION_SALE = 'LOADING_ACTION_SALE';
export const SET_VALUE_IN_CART_SALE = 'SET_VALUE_IN_CART';
export const RESET_CART_SALE = 'RESET_CART_SALE';
export const DELETE_CART_VALUE_SALE = 'DELETE_CART_VALUE_SALE';
export const SET_ACCOUNT_DATA_SALE = 'SET_ACCOUNT_DATA_SALE';
export const HANDLE_BACK_STEP_SALE = 'HANDLE_BACK_STEP_SALE';
export const SHOPING_AGAIN_SALE = 'SHOPING_AGAIN_SALE';
export const SET_BILL_INFO_DATA_SALE = 'SET_BILL_INFO_DATA_SALE';
export const SET_DISCOUNT_SALE = 'SET_DISCOUNT_SALE';
export const SET_DISCOUNT_IN_VALUE_SALE = 'SET_DISCOUNT_IN_VALUE_SALE';
export const GET_GYM_INFO_DATA_SALE = 'GET_GYM_INFO_DATA_SALE';
export const HANDLE_NEXT_STEP_SALE = 'HANDLE_NEXT_STEP_SALE';
export const SET_PAID_AMOUNT = 'SET_PAID_AMOUNT';


// Sms
export const FETCH_SMS_DATA = 'FETCH_SMS_DATA';
export const SEARCH_SMS_DATA = 'SEARCH_SMS_DATA';
export const EDIT_SMS_DATA = 'EDIT_SMS_DATA';
export const DELETE_SMS_DATA = 'DELETE_SMS_DATA';
export const ADD_SMS_DATA = 'ADD_SMS_DATA';
export const ERROR_SMS_DATA = 'ERROR_SMS_DATA';
export const SHOW_DETAIL_SMS = 'SHOW_DETAIL_SMS';
export const HIDE_DETAIL_SMS = 'HIDE_DETAIL_SMS';
export const SUBMIT_SMS_DATA = 'SUBMIT_SMS_DATA';
export const CLOSE_SMS_FORM = 'CLOSE_SMS_FORM';
export const TOGGLE_FAVORITE_SMS = 'TOGGLE_FAVORITE_SMS';
export const SET_SMS_DETAILS_FIELD = 'SET_SMS_DETAILS_FIELD';
export const LOADING_ACTION_SMS = 'LOADING_ACTION_SMS';
export const FETCH_SMS_ACTIVE_DATA = 'FETCH_SMS_ACTIVE_DATA';


// Subscription
export const FETCH_SUBSCRIPTION_DATA = 'FETCH_SUBSCRIPTION_DATA';
export const SEARCH_SUBSCRIPTION_DATA = 'SEARCH_SUBSCRIPTION_DATA';
export const EDIT_SUBSCRIPTION_DATA = 'EDIT_SUBSCRIPTION_DATA';
export const DELETE_SUBSCRIPTION_DATA = 'DELETE_SUBSCRIPTION_DATA';
export const ADD_SUBSCRIPTION_DATA = 'ADD_SUBSCRIPTION_DATA';
export const ERROR_SUBSCRIPTION_DATA = 'ERROR_SUBSCRIPTION_DATA';
export const SHOW_DETAIL_SUBSCRIPTION = 'SHOW_DETAIL_SUBSCRIPTION';
export const HIDE_DETAIL_SUBSCRIPTION = 'HIDE_DETAIL_SUBSCRIPTION';
export const SUBMIT_SUBSCRIPTION_DATA = 'SUBMIT_SUBSCRIPTION_DATA';
export const CLOSE_SUBSCRIPTION_FORM = 'CLOSE_SUBSCRIPTION_FORM';
export const TOGGLE_FAVORITE_SUBSCRIPTION = 'TOGGLE_FAVORITE_SUBSCRIPTION';
export const SET_SUBSCRIPTION_DETAILS_FIELD = 'SET_SUBSCRIPTION_DETAILS_FIELD';
export const LOADING_ACTION_SUBSCRIPTION = 'LOADING_ACTION_SUBSCRIPTION';
export const FETCH_SUBSCRIPTION_ACTIVE_DATA = 'FETCH_SUBSCRIPTION_ACTIVE_DATA';
