const formField = [
  { name: 'weight', placeLabel: 'Weight' },
  { name: 'height', placeLabel: 'Height' },
  { name: 'neck', placeLabel: 'Neck' },
  { name: 'shoulder', placeLabel: 'Shoulder' },
  { name: 'chestExtended', placeLabel: 'Chest Extended' },
  { name: 'chestNormal', placeLabel: 'Chest Normal' },
  { name: 'forearms', placeLabel: 'Forearms' },
  { name: 'biceps', placeLabel: 'Biceps' },
  { name: 'wrist', placeLabel: 'Wrist' },
  { name: 'upper', placeLabel: 'Upper' },
  { name: 'lower', placeLabel: 'Lower' },
  { name: 'waist', placeLabel: 'Waist' },
  { name: 'hip', placeLabel: 'Hip' },
  { name: 'thigh', placeLabel: 'Thigh' },
  { name: 'calves', placeLabel: 'Calves' },
  { name: 'ankles', placeLabel: 'Ankles' },
  { name: 'blood', placeLabel: 'Blood' },
  { name: 'sugar', placeLabel: 'Sugar' },
  { name: 'fat', placeLabel: 'Fat' },
  { name: 'bmi', placeLabel: 'Bmi' },
  { name: 'bmr', placeLabel: 'Bmr' },
  { name: 'medicalHistory', placeLabel: 'Medical History' },
];

export default formField;
