const addMemberDataField = [
  { primary: 'regNo', secondary: 'REGISTRATION NO' },
  { primary: 'name', secondary: 'NAME' },
  { primary: 'contact', secondary: 'CONTACT' },
  { primary: 'fTitle', secondary: 'FTITLE' },
  { primary: 'favourOf', secondary: 'FAVOUR OF' },
  { primary: 'alternativeContact', secondary: 'ALTERNATIVE CONTACT' },
  { primary: 'memberEmail', secondary: 'EMAIL' },
  { primary: 'dob', secondary: 'DATE OF BIRTH' },
  { primary: 'age', secondary: 'AGE' },
  { primary: 'address', secondary: 'ADDRESS' },
  { primary: 'occupation', secondary: 'OCCUPATION' },
  { primary: 'bloodGroup', secondary: 'BLOOD GROUP' },
  { primary: 'maritalStatus', secondary: 'MARITAL STATUS' },
  { primary: 'anniversary', secondary: 'ANNIVERSARY' },
  { primary: 'purpose', secondary: 'PURPOSE' },
  { primary: 'query', secondary: 'QUERY' },
  { primary: 'packageInfo', secondary: 'PACKAGE' },
  { primary: 'classInfo', secondary: 'CLASS' },
  { primary: 'packDisc', secondary: 'PACKAGE DISC' },
  { primary: 'classDisc', secondary: 'CLASS DISC' },
  { primary: 'classPrice', secondary: 'CLASS PRICE' },
  { primary: 'packPrice', secondary: 'PACKAGE PRICE' },
  { primary: 'payable', secondary: 'PAYABLE' },
  { primary: 'paidAmount', secondary: 'PAID AMOUNT' },
  { primary: 'balanceAmount', secondary: 'BALANCE AMOUNT' },
  { primary: 'paymentMode', secondary: 'PAYMENT MODE' },
  { primary: 'activation', secondary: 'ACTIVATION' },
  { primary: 'fingerCode', secondary: 'FINGER CODE' },
  { primary: 'referredBy', secondary: 'REFERRED BY' },
  { primary: 'packActivation', secondary: 'PACKAGE ACTIVATION' },
  { primary: 'classActivation', secondary: 'CLASS ACTIVATION' },
  { primary: 'status', secondary: 'STATUS' },
  { primary: '_id', secondary: '_id' }
];

export default addMemberDataField;
